environment:
  matrix:
    # http://www.appveyor.com/docs/installed-software#python
    - PYTHON: "C:\\Python27"
    - PYTHON: "C:\\Python33"
    - PYTHON: "C:\\Python34"
    - PYTHON: "C:\\Python35"
    - PYTHON: "C:\\Python36"
    - PYTHON: "C:\\Python37"

build: off

install:
  - "%PYTHON%\\python.exe -m pip install lxml"

test_script:
  - "%PYTHON%\\python.exe setup.py test"